### ISSUE TITLE
File/folder naming and structure

### ISSUE THREAD

**Issue by philsinatra** [karlysoldner/IDM-221#1]
You should strongly consider fixing your files and folders to follow standard naming conventions:
- all lower case
- no spaces

![screen shot 2016-10-20 at 8 29 35 am](https://cloud.githubusercontent.com/assets/1465808/19559782/816a519a-969f-11e6-922a-cb8b3840c984.png)

The folder _html and css_ can be simplified to something like _source_ or _files_.

Each of your .html files should be renamed to be all lowercase.

**Comment by philsinatra** [comment]
@karlysoldner No progress on this issue yet?

**Comment by karlysoldner** [comment]
My bad- totally missed your comment!

**Comment by philsinatra** [comment]
Looks good. Now you as the project owner can close the issue and note that the changes are complete. (you should rename the `Fonts` folder to be lowercase as well.
